### ISSUE TITLE
Change status bar color on debug

### ISSUE THREAD

**Issue by fabiojansenbr** [spaceinvadev/alternight-vscode-theme#6]
Hi.

I love this theme. Congratulations.

How i can change the statusBar color on debug session?

![image](https://user-images.githubusercontent.com/18349848/107818003-aa324100-6d55-11eb-9446-f9759ba1f854.png)

This orange color disturbs the text inside status bar.

Thanks

**Comment by spaceinvadev** [comment]
Hi, @fabiojansenbr. Thanks for reporting this issue. I just fixed it. In case you prefer a different color combination for the status bar in debug mode, you may use the below settings to customize them.

```json
"statusBar.debuggingBackground": "#e29fa4",
"statusBar.debuggingForeground": "#1f172b",
```
